#!/bin/sh

#
# Easy cscope with Git
# Based on: http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
#

set -e
PATH="/usr/bin:$PATH"
trap "rm -f .git/cscope.$$ .git/cscope.$$.in .git/cscope.$$.po" EXIT
cscope -Rbq -f .git/cscope.$$ 2>&1 >/dev/null
mv -f .git/cscope.$$ .git/cscope
mv -f .git/cscope.$$.in .git/cscope.in
mv -f .git/cscope.$$.po .git/cscope.po
