#!/bin/sh

#
# Easy ctags with Git
# Source: http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
#

set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT
ctags --tag-relative -Rf.git/tags.$$ --exclude=.git --languages=-javascript,sql 2>&1 >/dev/null
mv -f .git/tags.$$ .git/tags
